# Generated by Django 5.0.6 on 2024-06-03 16:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id'], 'verbose_name': 'Kitob ', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya ', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mijoz ', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Ijara ', 'verbose_name_plural': 'Ijaralar'},
        ),
        migrations.AddField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rent',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='miqdor'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app.category', verbose_name='kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(upload_to='%d_%m_%Y/', verbose_name='rasm'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(unique=True, verbose_name='isbn raqami'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='place',
            field=models.TextField(blank=True, null=True, verbose_name='joyi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_price',
            field=models.FloatField(default=0, verbose_name='ijara narxi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='place',
            field=models.TextField(blank=True, null=True, verbose_name='joyi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='ismi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_card',
            field=models.TextField(verbose_name='passport seriasi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='familiyasi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.TextField(verbose_name='manzili'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='miqdor'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.book', verbose_name='kitob'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='app.customer', verbose_name='mijoz'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='return_time',
            field=models.DateTimeField(verbose_name='qaytarish sanasi'),
        ),
    ]
